name: Linting and Unit Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set up Python 3.13
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv run pipenv install

    - name: Install test dependencies
      run: |
        pipenv run pipenv install --dev

    - name: Set .env file
      run: |
        cp .env.sample .env

    - name: Lint with flake8
      run: |
        pipenv run python -m flake8 . -v

    - name: Unit test with pytest
      run: |
        pipenv run pytest --ignore tests/end_to_end -v -m "not e2e"
